// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN4VahO61KMosO1Uzvdgu--nWhmBmpsH8',
    appId: '1:478707776314:web:ab38d0fa99e47507f4ae03',
    messagingSenderId: '478707776314',
    projectId: 'fitnestapp-6d9b4',
    authDomain: 'fitnestapp-6d9b4.firebaseapp.com',
    storageBucket: 'fitnestapp-6d9b4.appspot.com',
    measurementId: 'G-FPGT14HZXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASG45Sk0R7vQa8MJeDkDQSj0-2A9E4Txc',
    appId: '1:478707776314:android:c025eddc2918b954f4ae03',
    messagingSenderId: '478707776314',
    projectId: 'fitnestapp-6d9b4',
    storageBucket: 'fitnestapp-6d9b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQ-dQtjngs6GoeG0F9MYVr4j2B94C-Po',
    appId: '1:478707776314:ios:8adaf45d3cd486a9f4ae03',
    messagingSenderId: '478707776314',
    projectId: 'fitnestapp-6d9b4',
    storageBucket: 'fitnestapp-6d9b4.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQ-dQtjngs6GoeG0F9MYVr4j2B94C-Po',
    appId: '1:478707776314:ios:8adaf45d3cd486a9f4ae03',
    messagingSenderId: '478707776314',
    projectId: 'fitnestapp-6d9b4',
    storageBucket: 'fitnestapp-6d9b4.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN4VahO61KMosO1Uzvdgu--nWhmBmpsH8',
    appId: '1:478707776314:web:d59118cbfe36e985f4ae03',
    messagingSenderId: '478707776314',
    projectId: 'fitnestapp-6d9b4',
    authDomain: 'fitnestapp-6d9b4.firebaseapp.com',
    storageBucket: 'fitnestapp-6d9b4.appspot.com',
    measurementId: 'G-Y5DHWFKGNG',
  );
}
