// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCu3ihIZpU04fa4VtVgK9fY7pUAnFUw80',
    appId: '1:164333524285:web:56c8d3de76a0bbc407e154',
    messagingSenderId: '164333524285',
    projectId: 'test-650ad',
    authDomain: 'test-650ad.firebaseapp.com',
    storageBucket: 'test-650ad.appspot.com',
    measurementId: 'G-24DHR5CEMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkRx2Mc3h51VjbRaaOUawV3zN-noV4Jk',
    appId: '1:164333524285:android:59561d3fa4215c4f07e154',
    messagingSenderId: '164333524285',
    projectId: 'test-650ad',
    storageBucket: 'test-650ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LAVTqXzPiYxsBsa4KAsNfxJ8YURh5kE',
    appId: '1:164333524285:ios:4bcf7826766a035007e154',
    messagingSenderId: '164333524285',
    projectId: 'test-650ad',
    storageBucket: 'test-650ad.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LAVTqXzPiYxsBsa4KAsNfxJ8YURh5kE',
    appId: '1:164333524285:ios:4bcf7826766a035007e154',
    messagingSenderId: '164333524285',
    projectId: 'test-650ad',
    storageBucket: 'test-650ad.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCu3ihIZpU04fa4VtVgK9fY7pUAnFUw80',
    appId: '1:164333524285:web:3299814fe5f29cc107e154',
    messagingSenderId: '164333524285',
    projectId: 'test-650ad',
    authDomain: 'test-650ad.firebaseapp.com',
    storageBucket: 'test-650ad.appspot.com',
    measurementId: 'G-MMCLREL550',
  );

}